
auto := ScriptParser_Auto()

SPC_CLASS := auto()
SPC_COMMENTBLOCK := auto()
SPC_COMMENTMULTILINE := auto()
SPC_COMMENTSINGLELINE := auto()
SPC_FUNCTION := auto()
SPC_GETTER := auto()
SPC_INSTANCEMETHOD := auto()
SPC_INSTANCEPROPERTY := auto()
SPC_JSDOC := auto()
SPC_SETTER := auto()
SPC_STATICMETHOD := auto()
SPC_STATICPROPERTY := auto()
SPC_STRING := auto()
SPC_COMMENT := auto()
SPC_METHOD := auto()
SPC_PROPERTY := auto()
SPC_VARIABLE := auto()
